export default [
  [
    {
      caseDown: '`',
      caseUp: '~',
      code: 'Backquote',
      keycode: '192',
    },
    {
      caseDown: '1',
      caseUp: '!',
      code: 'Digit1',
      keycode: '49',
    },
    {
      caseDown: '2',
      caseUp: '@',
      code: 'Digit2',
      keycode: '50',
    },
    {
      caseDown: '3',
      caseUp: '#',
      code: 'Digit3',
      keycode: '51',
    },
    {
      caseDown: '4',
      caseUp: '$',
      code: 'Digit4',
      keycode: '52',
    },
    {
      caseDown: '5',
      caseUp: '%',
      code: 'Digit5',
      keycode: '53',
    },
    {
      caseDown: '6',
      caseUp: '^',
      code: 'Digit6',
      keycode: '54',
    },
    {
      caseDown: '7',
      caseUp: '&',
      code: 'Digit7',
      keycode: '55',
    },
    {
      caseDown: '8',
      caseUp: '*',
      code: 'Digit8',
      keycode: '56',
    },
    {
      caseDown: '9',
      caseUp: '(',
      code: 'Digit9',
      keycode: '57',
    },
    {
      caseDown: '0',
      caseUp: ')',
      code: 'Digit0',
      keycode: '48',
    },
    {
      caseDown: '-',
      caseUp: '_',
      code: 'Minus',
      keycode: '189',
    },
    {
      caseDown: '=',
      caseUp: '+',
      code: 'Equal',
      keycode: '187',
    },
    {
      caseDown: 'Backspace',
      caseUp: null,
      code: 'Backspace',
      keycode: '8',
    }
  ],
  [
    {
      caseDown: 'Tab',
      caseUp: null,
      code: 'Tab',
      keycode: '9',
    },
    {
      caseDown: 'q',
      caseUp: 'Q',
      code: 'KeyQ',
      keycode: '81',
    },
    {
      caseDown: 'w',
      caseUp: 'W',
      code: 'KeyW',
      keycode: '87',
    },
    {
      caseDown: 'e',
      caseUp: 'E',
      code: 'KeyE',
      keycode: '69',
    },
    {
      caseDown: 'r',
      caseUp: 'R',
      code: 'KeyR',
      keycode: '82',
    },
    {
      caseDown: 't',
      caseUp: 'T',
      code: 'KeyT',
      keycode: '84',
    },
    {
      caseDown: 'y',
      caseUp: 'Y',
      code: 'KeyY',
      keycode: '89',
    },
    {
      caseDown: 'u',
      caseUp: 'U',
      code: 'KeyU',
      keycode: '85',
    },
    {
      caseDown: 'i',
      caseUp: 'I',
      code: 'KeyI',
      keycode: '73',
    },
    {
      caseDown: 'o',
      caseUp: 'O',
      code: 'KeyO',
      keycode: '79',
    },
    {
      caseDown: 'p',
      caseUp: 'P',
      code: 'KeyP',
      keycode: '80',
    },
    {
      caseDown: '[',
      caseUp: '{',
      code: 'BracketLeft',
      keycode: '219',
    },
    {
      caseDown: ']',
      caseUp: '}',
      code: 'BracketRight',
      keycode: '221',
    },
    {
      caseDown: '\\',
      caseUp: '|',
      code: 'Backslash',
      keycode: '220',
    }
  ],
  [
    {
      caseDown: 'CapsLock',
      caseUp: null,
      code: 'CapsLock',
      keycode: '20',
    },
    {
      caseDown: 'a',
      caseUp: 'A',
      code: 'KeyA',
      keycode: '65',
    },
    {
      caseDown: 's',
      caseUp: 'S',
      code: 'KeyS',
      keycode: '83',
    },
    {
      caseDown: 'd',
      caseUp: 'D',
      code: 'KeyD',
      keycode: '68',
    },
    {
      caseDown: 'f',
      caseUp: 'F',
      code: 'KeyF',
      keycode: '70',
    },
    {
      caseDown: 'g',
      caseUp: 'G',
      code: 'KeyG',
      keycode: '71',
    },
    {
      caseDown: 'h',
      caseUp: 'H',
      code: 'KeyH',
      keycode: '72',
    },
    {
      caseDown: 'j',
      caseUp: 'J',
      code: 'KeyJ',
      keycode: '74',
    },
    {
      caseDown: 'k',
      caseUp: 'K',
      code: 'KeyK',
      keycode: '75',
    },
    {
      caseDown: 'l',
      caseUp: 'L',
      code: 'KeyL',
      keycode: '76',
    },
    {
      caseDown: ';',
      caseUp: ':',
      code: 'Semicolon',
      keycode: '186',
    },
    {
      caseDown: "'",
      caseUp: '"',
      code: 'Quote',
      keycode: '222',
    },
    {
      caseDown: 'Enter',
      caseUp: null,
      code: 'Enter',
      keycode: 13,
    }
  ],
  [
    {
      caseDown: 'Shift',
      caseUp: null,
      code: 'ShiftLeft',
      keycode: '16',
    },
    {
      caseDown: 'z',
      caseUp: 'Z',
      code: 'KeyZ',
      keycode: '90',
    },
    {
      caseDown: 'x',
      caseUp: 'X',
      code: 'KeyX',
      keycode: '88',
    },
    {
      caseDown: 'c',
      caseUp: 'C',
      code: 'KeyC',
      keycode: '67',
    },
    {
      caseDown: 'v',
      caseUp: 'V',
      code: 'KeyV',
      keycode: '86',
    },
    {
      caseDown: 'b',
      caseUp: 'B',
      code: 'KeyB',
      keycode: '66',
    },
    {
      caseDown: 'n',
      caseUp: 'N',
      code: 'KeyN',
      keycode: '78',
    },
    {
      caseDown: 'm',
      caseUp: 'M',
      code: 'KeyM',
      keycode: '77',
    },
    {
      caseDown: ',',
      caseUp: '<',
      code: 'Comma',
      keycode: '188',
    },
    {
      caseDown: '.',
      caseUp: '>',
      code: 'Period',
      keycode: '190',
    },
    {
      caseDown: '/',
      caseUp: '?',
      code: 'Slash',
      keycode: '191',
    },
    {
      caseDown: 'Shift',
      caseUp: null,
      code: 'ShiftRight',
      keycode: '16',
    }
  ],
  [
    {
      caseDown: 'Ctrl',
      caseUp: null,
      code: 'ControlLeft',
      keycode: '17',
    },
    {
      caseDown: 'Opt',
      caseUp: null,
      code: 'AltLeft',
      keycode: '18',
    },
    {
      caseDown: 'Cmd',
      caseUp: null,
      code: 'MetaLeft',
      keycode: '91',
    },
    {
      caseDown: ' ',
      caseUp: null,
      code: 'Space',
      keycode: '32',
    },
    {
      caseDown: 'Cmd',
      caseUp: null,
      code: 'MetaRight',
      keycode: '93',
    },
    {
      caseDown: 'Opt',
      caseUp: null,
      code: 'AltRight',
      keycode: '18',
    },
    {
      caseDown: '◀',
      caseUp: null,
      code: 'ArrowLeft',
      keycode: '37',
    },
    {
      caseDown: '▲',
      caseUp: null,
      code: 'ArrowUp',
      keycode: '38',
    },
    {
      caseDown: '▼',
      caseUp: null,
      code: 'ArrowDown',
      keycode: '40',
    },
    {
      caseDown: '▶',
      caseUp: null,
      code: 'ArrowRight',
      keycode: '39',
    }
  ]
];
