export default [
  [
    {
      caseDown: 'ё',
      caseUp: 'Ë',
      code: 'Backquote',
      keycode: '192',
    },
    {
      caseDown: '1',
      caseUp: '!',
      code: 'Digit1',
      keycode: '49',
    },
    {
      caseDown: '2',
      caseUp: '"',
      code: 'Digit2',
      keycode: '50',
    },
    {
      caseDown: '3',
      caseUp: '№',
      code: 'Digit3',
      keycode: '51',
    },
    {
      caseDown: '4',
      caseUp: ';',
      code: 'Digit4',
      keycode: '52',
    },
    {
      caseDown: '5',
      caseUp: '%',
      code: 'Digit5',
      keycode: '53',
    },
    {
      caseDown: '6',
      caseUp: ':',
      code: 'Digit6',
      keycode: '54',
    },
    {
      caseDown: '7',
      caseUp: '?',
      code: 'Digit7',
      keycode: '55',
    },
    {
      caseDown: '8',
      caseUp: '*',
      code: 'Digit8',
      keycode: '56',
    },
    {
      caseDown: '9',
      caseUp: '(',
      code: 'Digit9',
      keycode: '57',
    },
    {
      caseDown: '0',
      caseUp: ')',
      code: 'Digit0',
      keycode: '48',
    },
    {
      caseDown: '-',
      caseUp: '_',
      code: 'Minus',
      keycode: '189',
    },
    {
      caseDown: '=',
      caseUp: '+',
      code: 'Equal',
      keycode: '187',
    },
    {
      caseDown: 'Backspace',
      caseUp: null,
      code: 'Backspace',
      keycode: '8',
    }
  ],
  [
    {
      caseDown: 'Tab',
      caseUp: null,
      code: 'Tab',
      keycode: '9',
    },
    {
      caseDown: 'й',
      caseUp: 'Й',
      code: 'KeyQ',
      keycode: '81',
    },
    {
      caseDown: 'ц',
      caseUp: 'Ц',
      code: 'KeyW',
      keycode: '87',
    },
    {
      caseDown: 'У',
      caseUp: 'У',
      code: 'KeyE',
      keycode: '69',
    },
    {
      caseDown: 'к',
      caseUp: 'К',
      code: 'KeyR',
      keycode: '82',
    },
    {
      caseDown: 'е',
      caseUp: 'Е',
      code: 'KeyT',
      keycode: '84',
    },
    {
      caseDown: 'н',
      caseUp: 'Н',
      code: 'KeyY',
      keycode: '89',
    },
    {
      caseDown: 'г',
      caseUp: 'Г',
      code: 'KeyU',
      keycode: '85',
    },
    {
      caseDown: 'ш',
      caseUp: 'Ш',
      code: 'KeyI',
      keycode: '73',
    },
    {
      caseDown: 'щ',
      caseUp: 'Щ',
      code: 'KeyO',
      keycode: '79',
    },
    {
      caseDown: 'з',
      caseUp: 'З',
      code: 'KeyP',
      keycode: '80',
    },
    {
      caseDown: 'х',
      caseUp: 'Х',
      code: 'BracketLeft',
      keycode: '219',
    },
    {
      caseDown: 'ъ',
      caseUp: 'Ъ',
      code: 'BracketRight',
      keycode: '221',
    },
    {
      caseDown: '\\',
      caseUp: '/',
      code: 'Backslash',
      keycode: '220',
    }
  ],
  [
    {
      caseDown: 'CapsLock',
      caseUp: null,
      code: 'CapsLock',
      keycode: '20',
    },
    {
      caseDown: 'ф',
      caseUp: 'Ф',
      code: 'KeyA',
      keycode: '65',
    },
    {
      caseDown: 'ы',
      caseUp: 'Ы',
      code: 'KeyS',
      keycode: '83',
    },
    {
      caseDown: 'в',
      caseUp: 'В',
      code: 'KeyD',
      keycode: '68',
    },
    {
      caseDown: 'а',
      caseUp: 'А',
      code: 'KeyF',
      keycode: '70',
    },
    {
      caseDown: 'п',
      caseUp: 'П',
      code: 'KeyG',
      keycode: '71',
    },
    {
      caseDown: 'р',
      caseUp: 'Р',
      code: 'KeyH',
      keycode: '72',
    },
    {
      caseDown: 'о',
      caseUp: 'О',
      code: 'KeyJ',
      keycode: '74',
    },
    {
      caseDown: 'л',
      caseUp: 'Л',
      code: 'KeyK',
      keycode: '75',
    },
    {
      caseDown: 'д',
      caseUp: 'Д',
      code: 'KeyL',
      keycode: '76',
    },
    {
      caseDown: 'ж',
      caseUp: 'Ж',
      code: 'Semicolon',
      keycode: '186',
    },
    {
      caseDown: "э",
      caseUp: 'Э',
      code: 'Quote',
      keycode: '222',
    },
    {
      caseDown: 'Enter',
      caseUp: null,
      code: 'Enter',
      keycode: 13,
    }
  ],
  [
    {
      caseDown: 'Shift',
      caseUp: null,
      code: 'ShiftLeft',
      keycode: '16',
    },
    {
      caseDown: 'я',
      caseUp: 'Я',
      code: 'KeyZ',
      keycode: '90',
    },
    {
      caseDown: 'ч',
      caseUp: 'Ч',
      code: 'KeyX',
      keycode: '88',
    },
    {
      caseDown: 'с',
      caseUp: 'С',
      code: 'KeyC',
      keycode: '67',
    },
    {
      caseDown: 'м',
      caseUp: 'М',
      code: 'KeyV',
      keycode: '86',
    },
    {
      caseDown: 'и',
      caseUp: 'И',
      code: 'KeyB',
      keycode: '66',
    },
    {
      caseDown: 'т',
      caseUp: 'Т',
      code: 'KeyN',
      keycode: '78',
    },
    {
      caseDown: 'ь',
      caseUp: 'Ь',
      code: 'KeyM',
      keycode: '77',
    },
    {
      caseDown: 'б',
      caseUp: 'Б',
      code: 'Comma',
      keycode: '188',
    },
    {
      caseDown: 'ю',
      caseUp: 'Ю',
      code: 'Period',
      keycode: '190',
    },
    {
      caseDown: '.',
      caseUp: ',',
      code: 'Slash',
      keycode: '191',
    },
    {
      caseDown: 'Shift',
      caseUp: null,
      code: 'ShiftRight',
      keycode: '16',
    }
  ],
  [
    {
      caseDown: 'Ctrl',
      caseUp: null,
      code: 'ControlLeft',
      keycode: '17',
    },
    {
      caseDown: 'Option',
      caseUp: null,
      code: 'OptionLeft',
      keycode: '18',
    },
    {
      caseDown: 'Cmd',
      caseUp: null,
      code: 'MetaLeft',
      keycode: '91',
    },
    {
      caseDown: ' ',
      caseUp: null,
      code: 'Space',
      keycode: '32',
    },
    {
      caseDown: 'Cmd',
      caseUp: null,
      code: 'MetaRight',
      keycode: '93',
    },
    {
      caseDown: 'Option',
      caseUp: null,
      code: 'OptionRight',
      keycode: '18',
    },
    {
      caseDown: '◀',
      caseUp: null,
      code: 'ArrowLeft',
      keycode: '37',
    },
    {
      caseDown: '▲',
      caseUp: null,
      code: 'ArrowUp',
      keycode: '38',
    },
    {
      caseDown: '▼',
      caseUp: null,
      code: 'ArrowDown',
      keycode: '40',
    },
    {
      caseDown: '▶',
      caseUp: null,
      code: 'ArrowRight',
      keycode: '39',
    }
  ]
];
